#!/usr/bin/env ruby

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("./Gemfile", __dir__)
require "bundler/setup"
require "foobara/sh_cli_connector"
require_relative "capybaras"

connector = Foobara::CommandConnectors::ShCliConnector.new
connector.connect(FindAllCapybaras)
connector.connect(CreateCapybara)
connector.connect(UpdateCapybara)
connector.connect(DeleteAllCapybaras)

connector.run
