source "https://rubygems.org"

gem "foobara-agent" # , path: "../../agent"

# gem "foobara", path: "../../foobara"
# gem "foobara-util", path: "../../util"

gem "foobara-agent-cli", path: "../"
gem "foobara-anthropic-api"
gem "foobara-dotenv-loader"
gem "foobara-local-files-crud-driver"
gem "foobara-ollama-api"
gem "foobara-open-ai-api"
gem "foobara-sh-cli-connector"
gem "irb"
gem "pry"
gem "pry-byebug"
